name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Run the Docker image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build . --build-arg BOT_TOKEN=${{ secrets.BOT_TOKEN }} --file Dockerfile --tag mad_memes_ingest:$IMAGE_TAG
        docker run mad_memes_ingest:$IMAGE_TAG